# fly.toml file generated for remoteswitch on 2022-12-06T19:46:31+02:00

app = "remoteswitch"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NEXT_TELEMETRY_DISABLED = "1"
    DATABASE_URL = "file:/data/db/db.sqlite"

[env]
    PORT = "8080"
    NEXT_PUBLIC_CLIENTVAR = "clientvar"
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"
    DATABASE_URL = "file:/data/db/db.sqlite"
    NEXTAUTH_URL = "https://remoteswitch.net"
    WS_URL = "wss://remoteswitch.net"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source = "data"
  destination = "/data"


